# Generated by Django 4.2.1 on 2023-06-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_block_actual_weight_block_cbm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='block_weight',
            new_name='block_width',
        ),
    ]
