# Generated by Django 4.2.1 on 2023-06-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_rename_block_weight_block_block_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
